### ISSUE TITLE
Certificate generated for host accessible with IP generates warnings on client side

### ISSUE THREAD

**Issue by szewczyk-9ld** [ikreymer/certauth#8]
Passing ip address to generate_host_cert causes warnings on client side. Example warning 
obtained using python requests:

>  .../lib/python2.7/site-packages/urllib3/connection.py:362: SubjectAltNameWarning: Certificate for 10.9.4.XXX has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
>   SubjectAltNameWarning
> .../lib/python2.7/site-packages/urllib3/connection.py:362: SubjectAltNameWarning: Certificate for 10.9.4.XXX has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
>   SubjectAltNameWarning

Suggested change in generate_host_cert causes:
```# Workaround for openssh warning
    try:
        ipaddress.ip_address(host)
        alt_host = b'IP:' + host
    except ValueError:
        alt_host = b'DNS:' + host
    ...
```

**Comment by ikreymer** [comment]
Thanks for pointing this out!

Should now be fixed in 1.2.1

The IP check happens now happens in `load_cert()` and you should use that to obtain a certain (also takes care of wildcards and cacheing).
